Restapi
thulab/iot-benchmark pull request #428
Opened 2024-06-21 07:57 UTC by Wlh0

2024-06-21 11:06 UTC, SpriCoder requested changes
Some minor problems, PTAL~

2024-06-21 11:06 UTC, SpriCoder commented on configuration/conf/config.properties
> +# REST_AUTHORIZATION=Basic cm9vdDpyb290
Please add a comment of REST_AUTHORIZATION

2024-06-21 11:06 UTC, SpriCoder commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/IoTDBRestAPI.java
> +import okhttp3.*;
Please not use * here

2024-06-24 07:27 UTC, SpriCoder approved these changes
LGTM, And please paste a test result

2024-06-24 07:45 UTC, Wlh0 commented
![img_v3_02c5_1b0a6564-f249-4f75-bcc7-4ddab283f4eg](https://github.com/thulab/iot-benchmark/assets/53321767/650c4e55-47d0-40d3-b869-93a155340666)
![img_v3_02c5_d15266b4-0fde-48da-aaca-2ee445a2d74g](https://github.com/thulab/iot-benchmark/assets/53321767/e0a7e670-e86d-4d11-ae34-caa1efa9cd6c)

2024-06-24 07:48 UTC, merged