Strategy pattern
thulab/iot-benchmark pull request #438
Opened 2024-08-27 04:38 UTC by YangYumings

## Refactoring iotdb inheritance structure

### Brief change log
- delete IBechmarkSession.java
- delete ISessionDataSet.java
- delete IoTDBCluterSession.java
- delete IoTDBSessionBase.java
- merge IoTDBSessionBase.java and IoTDBSession.java

### Strategy Pattern

Model Strategy
- IoTDBModelStrategy.java
- TableStrategy.java
- TreeStrategy.java

Insert Strategy
- IoTDBInsertionStrategy
- JDBCStrategy
- SessionStrategy

### Does this pull request potentially affect one of the following parts:
- Tree mode and table mode

### Data cleanup
- Schema registration
- Session read operation
- Session write operation

2024-09-02 04:18 UTC, liyuheng55555 requested changes
< 1.3 的版本需要恢复 is all nodes visible 参数，

2024-09-02 04:18 UTC, liyuheng55555 commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +            : config.getDEVICE_NUMBER();
这里能想个更清楚的变量名吗

2024-09-02 04:18 UTC, liyuheng55555 commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +      tableAndDevice.computeIfAbsent(table, k -> new ArrayList<>()).add(deviceId);
Collections.singletonList?

2024-09-02 04:32 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/MetaUtil.java
> +        return (id + "").hashCode() % factor2;
又学到一招。

2024-09-02 04:34 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/DBWrapper.java
> +            // 树 表 的 records 一定不同。
这里我用英文描述一下吧。后续可能会用到，两个模型返回的矩阵中，列数是不同的，若要做点对点比较需要转换一下格式。

2024-09-02 04:36 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/utils/BlobUtils.java
> +  public static String bytesToHex(byte[] bytes) {
嗯嗯，我去修改。

2024-09-02 04:58 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/utils/BlobUtils.java
> +      e.printStackTrace();
好的

2024-09-02 05:00 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +        else config.setSQL_DIALECT("tree");
我手动改一下吧

2024-09-02 06:46 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +            : config.getDEVICE_NUMBER();
"deviceQueryMaxCount", 代表一个 select 中包含的最大设备数。目前单表查询时要保证每个需要查询的设备都在一张表中。

2024-09-02 07:12 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/entity/enums/ColumnCategory.java
> +  }
在Sensor的反序列化时使用到本方法。

2024-09-02 07:23 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +      tableAndDevice.computeIfAbsent(table, k -> new ArrayList<>()).add(deviceId);
这个不太行，应为 value 这个 list 不会仅存储一个值。当 key 不存在时，能新建一个包含一个值得 list 表示 value，当 key 存在时，在原有 value 得基础上 add 一个新的 kay。

2024-09-02 07:36 UTC, YangYumings commented on configuration/conf/config.properties
> +
这个暂时先不删哈

2024-09-02 07:37 UTC, liyuheng55555 commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +        else config.setSQL_DIALECT("tree");
我觉得加不加大括号都行，但最好还是条件语句和执行内容分行，容易看清楚

2024-09-02 07:46 UTC, liyuheng55555 commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/entity/enums/ColumnCategory.java
> +  }
ColumnCategory.values()[ordinal]跟这个函数效果一样吗

2024-09-02 07:48 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/utils/BlobUtils.java
> +      LOGGER.info(e.getMessage());
使用 error 更好。

2024-09-03 03:57 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/entity/enums/ColumnCategory.java
> +  }
一样的，都是从 0 开始，使用数据是 ok 的，而且还会更快。

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +  private static final Set<String> databases = Collections.synchronizedSet(new HashSet<>());
看起来不需要 synchronizedSet？

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +    Set<String> groups = new HashSet<>();
不要用 group 和 database 的命名来区分吧？含义应该是本线程负责创建的 dababase

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +      for (String database : tables.keySet()) {
使用 entrySet? 就不用再 .get 了？

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +    // test is the database name, g_0_table is the table name, and the device is the identification
g_0_table 在 "root.test.g_0.d_0.s_0" 里面没有吧？

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +  // TODO 用 count
这个暂时不好改吗

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +  private static final Set<String> storageGroups = Collections.synchronizedSet(new HashSet<>());
同上，如果底下用了 synchronized (IoTDB.class) { 是不是这里就不需要用了

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +      e.printStackTrace();
为啥这里不 handleRegisterException 或者打印一下日志啥的

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +    Set<String> groups = new HashSet<>();
同上

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +  // TODO 用 count
同上

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +    if (!e.getMessage().contains(IoTDB.ALREADY_KEYWORD) && !e.getMessage().contains("300")) {
这个是不是可以抽到父类里面当做一个 default 方法

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/QueryAndInsertionStrategy/IoTDBInsertionStrategy.java
> +        .version(Version.V_1_0)
是不是 130？

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/IoTDB.java
> +        paths.add(IoTDB.getSensorPath(deviceSchema, sensor.getName()));
1. 调本类的函数还需要 IoTDB. 吗？
2. 一定要用的话统一一下都小写用 iotdb 吧

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/IoTDB.java
> +
空行

2024-09-03 07:37 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/IoTDB.java
> +  public String typeMap(SensorType iotdbSensorType) {
这个是否需要重载？

2024-09-03 08:55 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/IoTDB.java
> +        paths.add(IoTDB.getSensorPath(deviceSchema, sensor.getName()));
已删除“IoTDB.”

2024-09-03 08:58 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/IoTDB.java
> +
已去除空行。

2024-09-03 09:09 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/schemaImpl/DeviceSchema.java
> +  /** Each device belongs to one table, i.e. database */
是的，注释复制过来后没有修改。

2024-09-03 09:14 UTC, YangYumings commented on configuration/conf/config.properties
> +# ANOTHER_IoTDB_ENABLE_TABLE=false
2. 好主意，使用 SQL_dialect 一个参数便能完成表模型与树模型的区分。

2024-09-03 10:03 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/DBFactory.java
> -          if (config.isIS_ALL_NODES_VISIBLE()) {
可以的，1.3 本身以及之前的版本保留此参数。

2024-09-03 10:03 UTC, YangYumings commented on configuration/conf/config.properties
> +# ANOTHER_IoTDB_ENABLE_TABLE=false
1.理解了；<br>2.好主意，使用 SQL_dialect 一个参数便能完成表模型与树模型的区分。

2024-09-03 10:03 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
> +  /** The number of table, In the tree model, it is equal to group_number */
表模型的两个映射使用同一个函数实现，为减少在此处做 sql_dialect 特判，树模型也是两次映射，不过第二次映射是一一映射。

2024-09-03 10:03 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
> +  public void setSQL_DIALECT(String sqlDialect) {
是的

2024-09-03 10:03 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +        if (config.getDbConfig().isIoTDB_ENABLE_TABLE()) {
👌

2024-09-03 10:03 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +          if (config.getANOTHER_DBConfig().isIoTDB_ENABLE_TABLE())
每天两个小技巧，养成编程好习惯。

2024-09-03 10:03 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +        if (config.getDbConfig().isIoTDB_ENABLE_TABLE()
可以合并；<br>1.确实，这样避免用户配置错误的参数；<br>2.没问题；

2024-09-03 10:04 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/schemaImpl/DeviceSchema.java
> +  /** Each device belongs to one table, i.e. database */
是的，注释复制过来后没有修改。

2024-09-03 10:04 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/DBConfig.java
> +  private boolean IoTDB_ENABLE_TABLE = false;
参考建议仅使用一个参数 sql_dialect 。

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/pom.xml
> +    <iotdb.version>1.4.0-SNAPSHOT</iotdb.version>
嗯嗯，等到复制 1.4 模块后，在 iotdb 1.3 回档到支持10中数据类型的 commit 。

2024-09-03 10:04 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +    Map<Integer, List<Integer>> tableAndDevice = new HashMap<>();
好主意。map 成为成员变量后，类在初始化阶段计算 map，然后在随机选择 device 阶段再从 map 中选取。

2024-09-03 10:04 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +      tableAndDevice.computeIfAbsent(table, k -> new ArrayList<>()).add(deviceId);
这里选择将其变为成员变量。

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/QueryAndInsertionStrategy/SessionStrategy.java
> +        if (line == 101) {
已删除。（之前排查问题时的语句，没有删除）

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/QueryAndInsertionStrategy/IoTDBInsertionStrategy.java
> +package cn.edu.tsinghua.iot.benchmark.iotdb130.QueryAndInsertionStrategy;
嗯嗯

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +  private static final Set<String> databases = Collections.synchronizedSet(new HashSet<>());
确实。同步块 synchronized (IoTDB.class) 使线程需要竞争本类中的所有静态变量。

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +    Set<String> groups = new HashSet<>();
嗯嗯。这样还可以从两个方法抽取公共部分。

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +      for (String database : tables.keySet()) {
已改为 entrySet 。

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +    // test is the database name, g_0_table is the table name, and the device is the identification
这里没有说清楚。我修改一下哈。

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +  // TODO 用 count
树表两个模型返回的 dataset 不同，表需要遍历一次 dataSet 来获得记录数。这导致处理 dataSet 的语句（在 sessionStrategy 中）会不同，所以我将两个模型都改成非 count 方式。然后在这里记了一个 TODO 提醒自己。<br>由于两种策略被 IoTDB.java 调用，若此处修改，可能会导致如下的调用关系出现：IoTDB -> TableStrategy 
 -> IoTDB -> SessionStrategy -> IoTDB ->TableStrategy 。不便于代码逻辑的理解。

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +  private static final Set<String> storageGroups = Collections.synchronizedSet(new HashSet<>());
嗯嗯，不需要了。

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +      e.printStackTrace();
已改为使用 handleRegisterException 打印日志

2024-09-03 10:04 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +    Set<String> groups = new HashSet<>();
改为database。

2024-09-03 10:05 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +  // TODO 用 count
树表两个模型返回的 dataset 不同，表需要遍历一次 dataSet 来获得记录数。这导致处理 dataSet 的语句（在 sessionStrategy 中）会不同，所以我将两个模型都改成非 count 方式。然后在这里记了一个 TODO 提醒自己。<br>由于两种策略被 IoTDB.java 调用，若此处修改，可能会导致如下的调用关系出现：IoTDB -> TableStrategy 
 -> IoTDB -> SessionStrategy -> IoTDB ->TableStrategy 。不便于代码逻辑的理解。

2024-09-03 10:05 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TreeStrategy.java
> +    if (!e.getMessage().contains(IoTDB.ALREADY_KEYWORD) && !e.getMessage().contains("300")) {
这个可以，我添加了一个 getLogger 方法，用来获取子类的 LOGGER，子类重写 getLogger 即可。如此将打印日志的逻辑抽到父类中。

2024-09-03 10:05 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/QueryAndInsertionStrategy/IoTDBInsertionStrategy.java
> +        .version(Version.V_1_0)
不太确认，这个枚举类很久没有维护了，最近一次是在 23 年 2 月。Version （iotdb_session 中）中目前有 V_1_0、V_0_13、V_0_11。觉得暂时可以设为 V_1_0 。

2024-09-03 10:05 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/IoTDB.java
> +        paths.add(IoTDB.getSensorPath(deviceSchema, sensor.getName()));
已删除 “IoTDB.”

2024-09-03 10:05 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/IoTDB.java
> +  public String typeMap(SensorType iotdbSensorType) {
这个不需要负载。已经在 IoTDB.java 中删除（应该是重写其他方法时，勾了全选）。

2024-09-03 10:06 UTC, liyuheng55555 commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/entity/enums/ColumnCategory.java
> +  }
那就直接用数组，给这个函数删了

2024-09-03 10:09 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/entity/enums/ColumnCategory.java
> +  }
嗯嗯，已经删除。

2024-09-04 04:32 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +        (config.getDbConfig().isIoTDB_ENABLE_TABLE()
在不支持双写的场景下，需要一个特判。树模型随机选择若干 device 用于查询，表模型从一个表中选择若干 device。等到表模型支持连表查询，这个特判便不再需要了。

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on configuration/conf/config.properties
> +# 在集群模式下：是否所有数据库都可见，如果可见则可以向其他数据库节点发送数据
这个没人用感觉就直接删掉吧？想用的人下载老版本的 bm 去用？没必要在未来一直保留这个参数

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on configuration/conf/config.properties
> +# 另一个写入数据库的sql_dialect, IoTDB 需指定 sql_dialect, 并且一个 IoTDB 只能指定一种。支持 tree、table,默认值为 tree。
目前还是支持一个表一个树双写吗？如果不支持就统一用上面的参数

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
> +  private boolean IS_ALL_NODES_VISIBLE = false;
可干掉？

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
> +    this.ANOTHER_DBConfig.setIoTDB_DIALECT_MODE(ANOTHER_IoTDB_DIALECT_MODE);
同上

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
> +    configProperties.addProperty("Other Param", "IS_ALL_NODES_VISIBLE", this.IS_ALL_NODES_VISIBLE);
同上

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +        config.setIS_ALL_NODES_VISIBLE(
同上

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +          config.setANOTHER_IoTDB_DIALECT_MODE(
同上

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +              "Please follow this rule to adjust the parameters: device number >= database number .");
说一下影响

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Constants.java
> +  public static final String IOTDB110_ROUNDROBIN_SESSION_CLASS =
还需要这个吗？现在似乎没这个类了？如果想用就用老版本的 bm 就行

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Constants.java
> +      "cn.edu.tsinghua.iot.benchmark.iotdb100.IoTDBClusterSession";
同上

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/DBFactory.java
> +          if (config.isIS_ALL_NODES_VISIBLE()) {
同上

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/DBFactory.java
> +          if (config.isIS_ALL_NODES_VISIBLE()) {
同上

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +  private static final Map<Integer, Set<Integer>> tableDeviceMap = new HashMap<>();
感觉得并发安全？底下没锁保护

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +  private static final Map<Integer, Set<Integer>> tableDeviceMap = new HashMap<>();
而且现在似乎是重复算了

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +        (config.getDbConfig().getIoTDB_DIALECT_MODE() == SQLDialect.TABLE
感觉双写这块又复杂了，要不直接干掉？

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDB.java
> +        if (!config.isIS_ALL_NODES_VISIBLE()) {
干掉

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/SingleNodeJDBCConnection.java
> +    if (config.isIS_ALL_NODES_VISIBLE()) {
干掉？

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDB.java
> +        if (!config.isIS_ALL_NODES_VISIBLE()) {
干掉？

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/SingleNodeJDBCConnection.java
> +    if (config.isIS_ALL_NODES_VISIBLE()) {
干掉？

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/IoTDBModelStrategy.java
> +  public void handleRegisterException(Exception e) throws TsdbException {
前面加个 default？

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/IoTDBModelStrategy.java
> +  public Set<String> getAllDataBase(List<TimeseriesSchema> schemaList) {
前面加个 default？

2024-09-04 10:20 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +      if (databaseName.contains(".")) {
这是是说不删除树模型 database 吗？我感觉这里的清理是不是跟测试之前 delete all data 一样？可能不用区分表模型不删树模型？ 
此外这里是不是重复删除 client 个数次了？可能得加到其它地方？

2024-09-04 11:11 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/TableStrategy.java
> +      if (databaseName.contains(".")) {
对，它是 delete all data，由主线程负责执行，只会走一次。session在初始化时指定了 sql_dialect，所以在表模型场景下，执行含有 . 的操作会出问题。所以这里我简单过滤一下。

2024-09-04 11:11 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/ModelStrategy/IoTDBModelStrategy.java
> +  public void handleRegisterException(Exception e) throws TsdbException {
可能不行，抽象类不能使用 default。

2024-09-04 11:11 UTC, YangYumings commented on iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/SingleNodeJDBCConnection.java
> +    if (config.isIS_ALL_NODES_VISIBLE()) {
干掉它

2024-09-04 11:11 UTC, YangYumings commented on iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDB.java
> +        if (!config.isIS_ALL_NODES_VISIBLE()) {
干掉它

2024-09-04 11:11 UTC, YangYumings commented on iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/SingleNodeJDBCConnection.java
> +    if (config.isIS_ALL_NODES_VISIBLE()) {
干掉它

2024-09-04 11:11 UTC, YangYumings commented on iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDB.java
> +        if (!config.isIS_ALL_NODES_VISIBLE()) {
干掉它

2024-09-04 11:11 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +        (config.getDbConfig().getIoTDB_DIALECT_MODE() == SQLDialect.TABLE
干掉它

2024-09-04 11:11 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Constants.java
> +      "cn.edu.tsinghua.iot.benchmark.iotdb100.IoTDBClusterSession";
已干掉

2024-09-04 11:12 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Constants.java
> +  public static final String IOTDB110_ROUNDROBIN_SESSION_CLASS =
已干掉

2024-09-04 11:13 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +              "Please follow this rule to adjust the parameters: device number >= database number .");
添加一句话：Otherwise, the total number of databases created is equal to the number of devices

2024-09-04 11:13 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +        config.setIS_ALL_NODES_VISIBLE(
干掉它

2024-09-04 11:13 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
> +    configProperties.addProperty("Other Param", "IS_ALL_NODES_VISIBLE", this.IS_ALL_NODES_VISIBLE);
干掉它

2024-09-04 11:13 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
> +  private boolean IS_ALL_NODES_VISIBLE = false;
干掉它

2024-09-04 13:13 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
> +    this.ANOTHER_DBConfig.setIoTDB_DIALECT_MODE(ANOTHER_IoTDB_DIALECT_MODE);
已干掉

2024-09-04 13:14 UTC, YangYumings commented on configuration/conf/config.properties
> +# 另一个写入数据库的sql_dialect, IoTDB 需指定 sql_dialect, 并且一个 IoTDB 只能指定一种。支持 tree、table,默认值为 tree。
将 IoTDB_ENABLE_TABLE 写到 config.java 中，并删除所有 ANOTHER_IoTDB_ENABLE_TABLE。

2024-09-05 03:03 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +  private static final Map<Integer, Set<Integer>> tableDeviceMap = new HashMap<>();
将初始化 tableDevicemap 的方法从构造函数中移除，然后把方法设为静态。这样每个实例从 map 中读取数据，便不用关注并发安全。

2024-09-05 04:22 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +          LOGGER.warn(
这里是不是忘加判断了？

2024-09-05 04:22 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +        if (config.getIoTDB_DIALECT_MODE() == SQLDialect.TREE) {
这个是不是直接塞 335 行就行

2024-09-05 04:43 UTC, OneSizeFitsQuorum reviewed
注意一下这个 PR 合进去之后新提一个 PR 把 1.3 的复原。
然后新的包不是 1.4 是 2.0 哈（表模型会发 2.0）

2024-09-05 04:43 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/DBWrapper.java
>                if (hasDifference(operation)) {
这里把非 measurement 列过滤掉就一样了？

2024-09-05 04:43 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +   * Return the list of deviceSchema TODO When multi-table query is supported, there is no need to
单独起一行 todo 吧

2024-09-05 04:43 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +    Integer[] devices = tableDeviceMap.get(tableId).toArray(new Integer[0]);
现在都静态计算没有冲突了，是不是没有必要 value 存一个 set，现在还得每次转换

2024-09-05 04:43 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/DMLStrategy/SessionStrategy.java
> +            IoTDB.constructDataTypes(
这种静态类感觉是不是搞个 Utils 类。。感觉 IoTDB.xxx 挺奇怪的

2024-09-05 04:43 UTC, OneSizeFitsQuorum commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/DMLStrategy/SessionStrategy.java
> +      if (session != null) session.close();
注意 if else 打括号，或者学学 optional

2024-09-05 07:25 UTC, YangYumings commented on iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/DMLStrategy/SessionStrategy.java
> +            IoTDB.constructDataTypes(
新增 IoTDBUtils.java 工具类，将 constructDataTypes 与 getDevicePath 移动到此工具类中。

2024-09-05 07:27 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
> +    Integer[] devices = tableDeviceMap.get(tableId).toArray(new Integer[0]);
是的，仅遍历一次 device，也不必使用 set 避免存储相同的设备 id。

2024-09-05 07:28 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/DBWrapper.java
>                if (hasDifference(operation)) {
是的。目前不支持双写比较树模型与表模型，所以我在这里写条注释，便于以后排除问题。

2024-09-05 07:53 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
> +          LOGGER.warn(
嗯嗯

2024-09-05 08:42 UTC, OneSizeFitsQuorum approved these changes
LGTM~
非常大的贡献！感谢耐心处理 review 意见！合作愉快！

2024-09-06 02:21 UTC, liyuheng55555 approved these changes
LGTM，作者和reviewer都辛苦了～ 非常好pr，使表模型旋转

2024-09-06 02:23 UTC, merged

2024-09-06 10:42 UTC, YangYumings commented
Thanks for reviewing!