The system shuts down automatically if the template creation fails.
thulab/iot-benchmark pull request #463
Opened 2024-11-22 07:55 UTC by YangYumings

原本在创建 template 完成前，所有的线程会被循环屏障阻塞在创建数据库之前。当 创建 template 的线程抛出异常会跳过countDown()，导致其余的线程无法退出。

- 方式
在 basemode 下设置 volatile flag，默认为 false, 当有线程抛出异常后将其改为 true；
当 basemode 发现 flag 为 true 时，输出日志，registerSchema（）返回 false，主线程结束；
为循环屏障设置超时时间 5s，超时后抛出异常然后结束线程。

2024-11-25 08:21 UTC, liyuheng55555 requested changes

2024-11-25 08:21 UTC, liyuheng55555 commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
> +  public static volatile boolean stopAllSchemaClient = false;
感觉加这个有点依赖全局变量了，不太优雅

目前看代码这个变量有两个作用，一是元数据注册线程之间的通信，二是BaseMode依赖这个变量判断是否注册成功

对于一，我问了chatgpt ”如果一个线程想让其它正在等待的线程出现异常该怎么做“，它说“调用 reset() 方法会打破当前的屏障，并使所有正在等待的线程抛出 BrokenBarrierException”

对于二，我看了一遍调用过程，是从BaseMode一层层调用到ModelStrategy的，最好通过返回值的方式去传达元数据注册是否成功

2024-11-25 08:21 UTC, liyuheng55555 commented on iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TreeStrategy.java
>        }
感觉没必要try多次？一个大try就行？

2024-11-25 08:33 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
> +  public static volatile boolean stopAllSchemaClient = false;
方法一：这种之前尝试过，reset 后其余的线程能顺利执行，但我觉得既然注册 template 都失败了，那注册 database、与实践序列也没有必要了。
方法二：这个方式逻辑上确实清晰，但这个可能需要把其他数据库得方法也要修改，改动的多一些，当失败后打印失败信息，然后直接 return false。

2024-11-25 08:35 UTC, YangYumings commented on iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TreeStrategy.java
>        }
使用多个 try 是保证每个屏障都能正确执行，防止死锁。不过要是使用上面提到的方法二，这里确实使用一个 try 就 ok。这样我去看看 方法二 都要修改哪些部分。

2024-11-25 09:02 UTC, liyuheng55555 commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
> +  public static volatile boolean stopAllSchemaClient = false;
其实不存在方法一、二之分吧，只是说如果不用全局变量的话怎么处理这俩问题
对于“reset 后其余的线程能顺利执行”，reset后其它线程应该是否为BrokenBarrierException？catch到这个异常就不继续执行
对于“其他数据库得方法也要修改”，这个确实是个问题，能否给registerSchema接口改一下让接口抛异常？其它数据库的实现就不用改了

2024-11-25 11:30 UTC, OneSizeFitsQuorum commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
> +  public static volatile boolean stopAllSchemaClient = false;
| 对于“reset 后其余的线程能顺利执行”，reset后其它线程应该是否为BrokenBarrierException？catch到这个异常就不继续执行

感觉可以按照这个搞？如果是这样的话那就处理一下异常就行，不用额外维护一个全局变量，可能更清晰？

2024-11-25 11:31 UTC, OneSizeFitsQuorum commented on iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TreeStrategy.java
>        }
如果上款用 reset 的话应该就用一个就行？

2024-11-25 13:10 UTC, YangYumings commented on core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
> +  public static volatile boolean stopAllSchemaClient = false;
使用方法一。

2024-11-25 13:28 UTC, OneSizeFitsQuorum approved these changes
LGTM

2024-11-25 13:28 UTC, merged

2024-11-26 02:11 UTC, liyuheng55555 reviewed
LGTM. Nice and clear~